#!/usr/bin/env bash
# VF (2x) & VF+HV (3x) cold-start, rho=30..100. Edit cuda:0 -> your GPU per line.
# rho<100 : each line = ONE seed x its lr-grid, 1 run/cell (variance from 5 seeds).
# rho=100 : seed-independent -> SINGLE seed (42), but 6 runs/lr (variance from runs,
#           matching aug1/aug2/aug4 rho=100). One line per lr, inner loop x6.
# Safe to re-run: max_runs=6 guard skips already-full cells.

### ===== VF  (exp_path aug_curve/vf2) =====
## vf rho=30  (1 run/cell, 5 seeds; lrs: 0.0003 0.001 0.003)
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 30 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 30 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 30 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 30 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 30 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done

## vf rho=40  (1 run/cell, 5 seeds; lrs: 0.0003 0.001 0.003)
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 40 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 40 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 40 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 40 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 40 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done

## vf rho=50  (1 run/cell, 5 seeds; lrs: 0.0003 0.0005 0.001)
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 50 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 50 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 50 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 50 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 50 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done

## vf rho=60  (1 run/cell, 5 seeds; lrs: 0.0003 0.0005 0.001)
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 60 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 60 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 60 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 60 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 60 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done

## vf rho=70  (1 run/cell, 5 seeds; lrs: 0.0003 0.001)
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 70 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 70 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 70 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 70 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 70 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done

## vf rho=80  (1 run/cell, 5 seeds; lrs: 0.0003 0.001)
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 80 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 80 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 80 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 80 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 80 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done

## vf rho=90  (1 run/cell, 5 seeds; lrs: 0.0003 0.001)
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 90 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 90 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 90 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 90 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 90 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done

## vf rho=100  (single seed 42, 6 runs/lr; lrs: 0.0003 0.001)
for i in 1 2 3 4 5 6; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 100 --seed 42 --lr 0.0003 --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done
for i in 1 2 3 4 5 6; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vf --portion 100 --seed 42 --lr 0.001 --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vf2; done

### ===== VFHV  (exp_path aug_curve/vfhv3) =====
## vfhv rho=30  (1 run/cell, 5 seeds; lrs: 0.0003 0.001 0.003)
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 30 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 30 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 30 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 30 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 30 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done

## vfhv rho=40  (1 run/cell, 5 seeds; lrs: 0.0003 0.001 0.003)
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 40 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 40 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 40 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 40 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001 0.003; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 40 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done

## vfhv rho=50  (1 run/cell, 5 seeds; lrs: 0.0003 0.0005 0.001)
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 50 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 50 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 50 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 50 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 50 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done

## vfhv rho=60  (1 run/cell, 5 seeds; lrs: 0.0003 0.0005 0.001)
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 60 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 60 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 60 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 60 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.0005 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 60 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done

## vfhv rho=70  (1 run/cell, 5 seeds; lrs: 0.0003 0.001)
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 70 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 70 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 70 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 70 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 70 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done

## vfhv rho=80  (1 run/cell, 5 seeds; lrs: 0.0003 0.001)
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 80 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 80 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 80 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 80 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 80 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done

## vfhv rho=90  (1 run/cell, 5 seeds; lrs: 0.0003 0.001)
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 90 --seed 10 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 90 --seed 24 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 90 --seed 38 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 90 --seed 42 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for LR in 0.0003 0.001; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 90 --seed 57 --lr $LR --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done

## vfhv rho=100  (single seed 42, 6 runs/lr; lrs: 0.0003 0.001)
for i in 1 2 3 4 5 6; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 100 --seed 42 --lr 0.0003 --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done
for i in 1 2 3 4 5 6; do python3 thesis/chapter_5/segmentation/run_first_iter.py --dataroot ./ds/segmentation --epoch 25 --batch_size 8 --max_runs 6 --device cuda:0 --flip_set vfhv --portion 100 --seed 42 --lr 0.001 --exp_path ./thesis/chapter_5/segmentation/exp_results/aug_curve/vfhv3; done

